spring:
  redis:
    #连接的是第0个库
    database: 0
    #ip地址
    host: 47.102.136.26
    #端口号
    port: 6379
    #密码
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
